// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/16/2024, 10:19:28 AM
const configMerger = require("/Users/deann2/Desktop/tcw/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/deann2/Desktop/tcw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/plugins/**/*.{js,ts,mjs}","/Users/deann2/Desktop/tcw/composables/**/*.{js,ts,mjs}","/Users/deann2/Desktop/tcw/utils/**/*.{js,ts,mjs}","/Users/deann2/Desktop/tcw/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/deann2/Desktop/tcw/app.config.{js,ts,mjs}"] } }));

module.exports = config
